/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jacky_jni_JniTest */

#ifndef _Included_com_jacky_jni_JniTest
#define _Included_com_jacky_jni_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jacky_jni_JniTest
 * Method:    getJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jacky_jni_JniTest_getJniString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
